### PR TITLE
Enum Array List Parceling

### PR DESCRIPTION
**Pull request by KennethNickles**
Added the ability for the ArrayListParceler to parcel Arrays with Enums

### CODE REVIEW

**Comment by KennethNickles** [comment]
@ndtaylor what formatter are you using for this project? Getting a check style error.

**Comment by KennethNickles** [comment]
> @ndtaylor what formatter are you using for this project? Getting a check style error.

Nevermind I found your code style xml file. I'll patch this PR asap. On another note the tests for handling array lists of enums seems to be working but prior to this change I saw exceptions thrown by the annotation processor when trying to handle array lists of enums. Does there need to be an update around that logic? And if so, where do I find that code?

**Comment by ndtaylor** [comment]
I'll take a look this evening and let you know.

**Comment by KennethNickles** [comment]
Postman 1.2 added relevant functionality

**Pull request closed without merging**
